// This file was generated by liblab | https://liblab.com/

import {
  BlockAvailabilityInputDto,
  GetBlockAvailabilityAccept,
  GetHotelAvailabilityAccept,
  GetHotelThemeTypesAccept,
  GetHotelTypesAccept,
  GetHotelsAccept,
  GetHotelsReviewScoresAccept,
  GetRoomFacilityTypesAccept,
  HotelAvailabilityInputDto,
  HotelFacilityInputDto,
  HotelThemeTypeInputDto,
  HotelTypeInputDto,
  HotelsInputDto,
  ReviewScoresInputDto,
  blockAvailabilityInputDto,
  getBlockAvailabilityAccept,
  getHotelAvailabilityAccept,
  getHotelThemeTypesAccept,
  getHotelTypesAccept,
  getHotelsAccept,
  getHotelsReviewScoresAccept,
  getRoomFacilityTypesAccept,
  hotelAvailabilityInputDto,
  hotelFacilityInputDto,
  hotelThemeTypeInputDto,
  hotelTypeInputDto,
  hotelsInputDto,
  reviewScoresInputDto,
} from './models';

export interface GetHotelsReviewScoresParams {
  reviewScoresInputDto: ReviewScoresInputDto;
  accept?: GetHotelsReviewScoresAccept;
}

export interface GetHotelsParams {
  hotelsInput: HotelsInputDto;
  accept?: GetHotelsAccept;
}

export interface GetHotelTypesParams {
  hotelTypeInputDto: HotelTypeInputDto;
  accept?: GetHotelTypesAccept;
}

export interface GetHotelThemeTypesParams {
  hotelThemeTypeInputDto: HotelThemeTypeInputDto;
  accept?: GetHotelThemeTypesAccept;
}

export interface GetRoomFacilityTypesParams {
  hotelFacilityInputDto: HotelFacilityInputDto;
  accept?: GetRoomFacilityTypesAccept;
}

export interface GetHotelAvailabilityParams {
  hotelAvailabilityInputDto: HotelAvailabilityInputDto;
  accept?: GetHotelAvailabilityAccept;
}

export interface GetBlockAvailabilityParams {
  blockInput: BlockAvailabilityInputDto;
  accept?: GetBlockAvailabilityAccept;
}
