// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const facilityDtoAttributes = z.enum(['OFFSITE', 'PAID']);

export type FacilityDtoAttributes = z.infer<typeof facilityDtoAttributes>;
