// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { cancellationDto, cancellationDtoRequest, cancellationDtoResponse } from './cancellation-dto';
import { mealPlanDto, mealPlanDtoRequest, mealPlanDtoResponse } from './meal-plan-dto';
import { paymentDto, paymentDtoRequest, paymentDtoResponse } from './payment-dto';

/**
 * The shape of the model inside the application code - what the users use
 */
export const policiesDto: any = z.lazy(() => {
  return z.object({
    cancellation: cancellationDto.optional(),
    mealPlan: mealPlanDto.optional(),
    payment: paymentDto.optional(),
  });
});

/**
 * The policies for this product.
 * @typedef  {PoliciesDto} policiesDto - The policies for this product. - The policies for this product.
 * @property {CancellationDto} - The cancellation policy for this product.
 * @property {MealPlanDto} - The meal plan policy for this product.
 * @property {PaymentDto} - Payment terms and conditions for this product.
 */
export type PoliciesDto = z.infer<typeof policiesDto>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const policiesDtoResponse: any = z.lazy(() => {
  return z
    .object({
      cancellation: cancellationDtoResponse.optional(),
      meal_plan: mealPlanDtoResponse.optional(),
      payment: paymentDtoResponse.optional(),
    })
    .transform((data) => ({
      cancellation: data['cancellation'],
      mealPlan: data['meal_plan'],
      payment: data['payment'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const policiesDtoRequest: any = z.lazy(() => {
  return z
    .object({
      cancellation: cancellationDtoRequest.nullish(),
      mealPlan: mealPlanDtoRequest.nullish(),
      payment: paymentDtoRequest.nullish(),
    })
    .transform((data) => ({
      cancellation: data['cancellation'],
      meal_plan: data['mealPlan'],
      payment: data['payment'],
    }));
});
