// This file was generated by liblab | https://liblab.com/

import { BookerInputDto, Booking, Coordinates, GuestsInputDto, SearchInputDto } from 'booking';

(async () => {
  const booking = new Booking({
    token: 'YOUR_TOKEN',
  });

  const accept = SearchAccept.application / json;

  const platform = Platform.ANDROID;

  const travelPurpose = TravelPurpose.BUSINESS;

  const userGroups = UserGroups.AUTHENTICATED;

  const bookerInputDto: BookerInputDto = {
    country: 're',
    platform: platform,
    travelPurpose: travelPurpose,
    userGroups: [userGroups],
  };

  const allocationInputDto: AllocationInputDto = {
    children: [5],
    numberOfAdults: 9,
  };

  const guestsInputDto: GuestsInputDto = {
    numberOfAdults: 4,
    numberOfRooms: 8,
    allocation: [allocationInputDto],
    children: [16],
  };

  const searchInputDtoExtras = SearchInputDtoExtras.EXTRA_CHARGES;

  const coordinates: Coordinates = {
    latitude: 4.04,
    longitude: 5.18,
    radius: 7.55,
  };

  const input: SearchInputDto = {
    checkin: 'checkin',
    checkout: 'checkout',
    booker: bookerInputDto,
    currency: 'EUR',
    city: 6,
    country: 'nl',
    guests: guestsInputDto,
    extras: [searchInputDtoExtras],
    accommodations: [9],
    accommodationFacilities: [4],
    roomFacilities: [6],
    accommodationTypes: [5],
    brands: [5],
    airport: 'AMS',
    district: 8,
    landmark: 8,
    coordinates: coordinates,
    region: 4,
    rows: 294,
    page: 'page',
  };

  const { data } = await booking.demandApiV3Compatible.search(input, {
    accept: accept,
  });

  console.log(data);
})();
