// This file was generated by liblab | https://liblab.com/

import {
  GetAccommodationConstantsAccept,
  PostDetailsAccept,
  SearchAccept,
  getAccommodationConstantsAccept,
  postDetailsAccept,
  searchAccept,
} from './models';

export interface SearchParams {
  accept?: SearchAccept;
}

export interface PostDetailsParams {
  accept?: PostDetailsAccept;
}

export interface GetAccommodationConstantsParams {
  accept?: GetAccommodationConstantsAccept;
}
