// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getHotelsAccept = z.enum(['application/json, application/xml']);

export type GetHotelsAccept = z.infer<typeof getHotelsAccept>;
