// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getHotelsReviewScoresAccept = z.enum(['application/json, application/xml']);

export type GetHotelsReviewScoresAccept = z.infer<typeof getHotelsReviewScoresAccept>;
