// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getHotelTypesAccept = z.enum(['application/json']);

export type GetHotelTypesAccept = z.infer<typeof getHotelTypesAccept>;
