// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getHotelAvailabilityAccept = z.enum(['application/json']);

export type GetHotelAvailabilityAccept = z.infer<typeof getHotelAvailabilityAccept>;
